### [ 축 변경 ] <hr>

- shape속성에 튜플 값의 순서를 변경
    * 2D shape은 (행, 열)
    * 3D shape은 (깊이, 행, 열)
    * 4D shape은 (개수, 깊이, 행, 열)
- 원소 개수 변경 X, 차원 변경 X
- 속성: ndarray.T
- 메서드: ndarray.transpose(*축들)/ ndarray.swapaxes(축1, 축2)

In [ ]:
# ---------------------------------------
# 모듈 로딩
# ---------------------------------------

import numpy as np


In [ ]:
# ---------------------------------------
# 실습 array 생성
# ---------------------------------------

a1= np.arange(1, 9).reshape(2, 4)
a2= np.arange(1, 5, 0.25 ).reshape(1, 4, -1)


print(a1.shape, a2.shape, a3.shape)

(2, 4) (4, 1) (1, 4)


In [8]:
# ---------------------------------------
# 행렬 내적 연산- (1) np.matmul()/ @
# ---------------------------------------
a12= np.matmul(a1, a2)
print("a12", a12, sep= '\n')

# np.matmul(a1, a3) ---> 행렬 식이 안 맞아서 에러뜸

a13= np.matmul(a1, a3.T) 
print("a13", a13, sep= '\n')
 

op= a1 @ a2
print("op====>", op, sep='\n')

a12
[[30]
 [70]]
a13
[[30]
 [70]]
op====>
[[30]
 [70]]


In [9]:
# ---------------------------------------
# 행렬 외적 연산- (2) np.outer()/ @
# ---------------------------------------
a12= np.outer(a1, a2)
print("a12", a12, sep= '\n')

# np.matmul(a1, a3) ---> 행렬 식이 안 맞아서 에러뜸

a13= np.outer(a1, a3.T) 
print("a13", a13, sep= '\n')
 

a12
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]
a13
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]


In [13]:
# ---------------------------------------
# 필터링- (2) np.all(): 필터링 된 인덱스
# ---------------------------------------

arr2d= arr1d.reshape(-1, 10)

print("axis=None", np.all(arr1d%2), np.any(arr2d%2))
print("axis=1", np.all(arr2d%2, axis=1), np.any(arr2d%2, axis=1))

axis=None False True
axis=1 [False False False] [ True  True  True]
