### [ 정렬 & arg 함수명() ] <hr>

- 함수: np.sort()=> [기] 오름차순 정렬된 ndarray 반환
- 매서드: ndarray.sort()=> 원본 정렬
 
- arg000() 함수: 
    * 해당 값이 있는 인덱스 반환(값 반환 아님)
    * 예: ndarray.max(): 원소 중 가장 큰 값
    * 예: ndarray.argmax(): 원소 중 가장 큰 값의 인덱스

In [1]:
# ---------------------------------------
# 모듈 로딩
# ---------------------------------------

import numpy as np


In [3]:
# ---------------------------------------
# 실습 array 생성
# ---------------------------------------

a1= np.array([[3, 1, 6],
               [0, 7, 4],
               [5, 3, 2]])

print(a1)

[[3 1 6]
 [0 7 4]
 [5 3 2]]


In [6]:
# ---------------------------------------
# 정렬
# ---------------------------------------
as1= np.sort(a1)

print("a1====>", a1.shape, a1, sep= '\n')
print("as1====>", as1.shape, as1, sep= '\n')

## 매서드: 원본이 바뀜
a1.sort()
print(a1)


a1====>
(3, 3)
[[1 3 6]
 [0 4 7]
 [2 3 5]]
as1====>
(3, 3)
[[1 3 6]
 [0 4 7]
 [2 3 5]]
[[1 3 6]
 [0 4 7]
 [2 3 5]]


In [ ]:
# ---------------------------------------
# 행렬 외적 연산- (2) np.outer()/ @
# ---------------------------------------
a12= np.outer(a1, a2)
print("a12", a12, sep= '\n')

# np.matmul(a1, a3) ---> 행렬 식이 안 맞아서 에러뜸

 

a12
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]
a13
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]


In [13]:
# ---------------------------------------
# 필터링- (2) np.all(): 필터링 된 인덱스
# ---------------------------------------

arr2d= arr1d.reshape(-1, 10)

print("axis=None", np.all(arr1d%2), np.any(arr2d%2))
print("axis=1", np.all(arr2d%2, axis=1), np.any(arr2d%2, axis=1))

axis=None False True
axis=1 [False False False] [ True  True  True]
