### [ array 필터링 ] <hr>

- BooleanIndexing
- 함수: np.where( array[조건식] )=> 조건에 맞는 데이터/ 원소의 인덱스 튜플로 반환


In [1]:
# ---------------------------------------
# 모듈 로딩
# ---------------------------------------

import numpy as np


In [4]:
# ---------------------------------------
# 실습 array 생성
# ---------------------------------------

arr1d= np.arange(1, 31)

print(arr1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [6]:
# ---------------------------------------
# 필터링- (1) Boolean Indexing
# ---------------------------------------

bool_idx= arr1d%2==0

arr1d[bool_idx]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [10]:
# ---------------------------------------
# 필터링- (2) np.where(): 필터링 된 인덱스
# ---------------------------------------
filtering_idx= np.where(~arr1d%2)

arr1d[filtering_idx]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [13]:
# ---------------------------------------
# 필터링- (2) np.all(): 필터링 된 인덱스
# ---------------------------------------

arr2d= arr1d.reshape(-1, 10)

print("axis=None", np.all(arr1d%2), np.any(arr2d%2))
print("axis=1", np.all(arr2d%2, axis=1), np.any(arr2d%2, axis=1))

axis=None False True
axis=1 [False False False] [ True  True  True]


In [14]:
# ---------------------------------------
# ravel(): 데이터 공유, view 생성
# ---------------------------------------

f= arr3d.ravel()

# 원소값 변경
arr3d[0, 0, 2]= -333

print(arr3d, f, sep='\n\n')

[[[ 100  200 -333]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]

 [[  13   14   15]
  [  16   17   18]]

 [[  19   20   21]
  [  22   23   24]]

 [[  25   26   27]
  [  77   77   77]]]

[ 100  200 -333    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   77
   77   77]
