### [ array 연산 ] <hr>

- 원소 단위(Elemant-wise) 연산
    * 같은 인덱스의 원소끼리 연산 진행
    * 숫자와 사이 array 연산=> 숫지를 벡터화 한 후 수행

In [1]:
# ---------------------------------------
# 모듈 로딩
# ---------------------------------------

import numpy as np
arr1d= np.array([10, 20, 30])
arr2d= np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print(arr1d, arr2d, sep='\n\n')

[10 20 30]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# -----------------------------
# 기본 산술 연산
# -----------------------------

# => array와 숫자 데이터 연산
print(f' {arr1d} + 5= {arr1d+5}')
print(f' {arr1d} - 5= {arr1d-5}')
print(f' {arr1d} / 5= {arr1d/5}')
print(f' {arr1d} * 5= {arr1d*5}')

 [10 20 30] + 5= [15 25 35]
 [10 20 30] - 5= [ 5 15 25]
 [10 20 30] / 5= [2. 4. 6.]
 [10 20 30] * 5= [ 50 100 150]


In [4]:
# -----------------------------
# 비교 연산
# -----------------------------

# => array와 숫자 데이터 연산
print(f' {arr1d} == 5= {arr1d==5}')
print(f' {arr1d} != 5= {arr1d != 5}')
print(f' {arr1d} <= 5= {arr1d<= 5}')
print(f' {arr1d} >= 5= {arr1d>=5}')

 [10 20 30] == 5= [False False False]
 [10 20 30] != 5= [ True  True  True]
 [10 20 30] <= 5= [False False False]
 [10 20 30] >= 5= [ True  True  True]


In [10]:
# -----------------------------
# Numpy 제공 수학 관련 함수들
# -----------------------------

# => array와 숫자 데이터 연산
print(f' {arr1d}=> np.sqrt(arr1d): {np.sqrt(arr1d)}')
print(f' {arr1d}=> np.log(arr1d): {np.log(arr1d)}')
print(f'np.pi: {np.pi}')


 [10 20 30]=> np.sqrt(arr1d): [3.16227766 4.47213595 5.47722558]
 [10 20 30]=> np.log(arr1d): [2.30258509 2.99573227 3.40119738]
np.pi: 3.141592653589793


In [12]:
# ---------------------------------------------
# Numpy 제공 집계 관련 함수들 => 축 설정 필수(axis)
#  - axis=0: 열 단위 집계
#  - axis=1: 행 단위 집계
# ---------------------------------------------

print(arr2d)
print(f'모든 원소 합계: {arr2d.sum()}')
print(f'열 방향 합계: {arr2d.sum(axis=0)}')
print(f'행 방향 합계: {arr2d.sum(axis=1)}')


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
모든 원소 합계: 78
열 방향 합계: [15 18 21 24]
행 방향 합계: [10 26 42]


In [14]:
print(f'모든 원소 최대값: {arr2d.max()}')
print(f'열 방향 최대값: {arr2d.max(axis=0)}')
print(f'행 방향 최대값: {arr2d.max(axis=1)}')

모든 원소 최대값: 12
열 방향 최대값: [ 9 10 11 12]
행 방향 최대값: [ 4  8 12]
