### [ array 원소 추출 ] <hr>
- 인덱스 기반 원소 추출
    * 1차원 배열: 변수명[인덱스]
    * 2차원 배열: 변수명[행인덱스] - 행 추출, 변수명[행인덱스, 열인덱스], 변수명[행인덱스, 열인덱스]- 원소 추출
- 팬시 인덱싱 기반 원소 추출
    * 비연속적, 비규칙적 원소 추출 시 사용
    * [인덱스, 인덱스, ...]
    * 원소 추출: [행 인덱스1, 행 인덱스2], [열 인덱스1, 열 인덱스2]
        - [행 인덱스1, 열 인덱스1], [행 인덱스2, 열 인덱스2]
    * 교차 원소 추출: np.ix_([행 인덱스1, 행 인덱스2], [열 인덱스1, 열 인덱스2])

In [5]:
# -------------------------------
# 특정 값으로 array 생성
# -------------------------------

import numpy as np

arr2d= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# -------------------------------
# 특정 행 추출
# -------------------------------
arr2d[[1, 2]]


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# -------------------------------
# 특정 값 추출
# -------------------------------
arr2d[0][1], arr2d[0, 1], arr2d[1][2], arr2d[2, 3]

(np.int64(2), np.int64(2), np.int64(7), np.int64(12))

In [10]:
# -------------------------------
# 대각선 관련 array 생성
# -------------------------------
base= np.array([[11, 22, 33], [44, 55, 66]])

arr1= np.eye(5)
arr2= np.eye(5, 3)
arr3= np.full_like(base, 3)
arr3= np.diag([3, 5, 7])
print(arr1, arr2, arr3, sep='\n\n')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[3 0 0]
 [0 5 0]
 [0 0 7]]


In [11]:
# -------------------------------
# 대각선 관련 array 생성
# -------------------------------
base= np.array([[11, 22, 33], [44, 55, 66]])

arr1= np.eye(5)
arr2= np.eye(5, 3)
arr3= np.full_like(base, 3)
arr3= np.diag([3, 5, 7])
arr4= np.diag([[3, 5, 7],[2, 4, 8]])
print(arr1, arr2, arr3, arr4, sep='\n\n')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[3 0 0]
 [0 5 0]
 [0 0 7]]

[3 4]
