## [ 정렬 & arg함수명() ] <hr>

- 함__수 : np.sort() => [기] 오름차순 정렬된 ndarray 반환
- 메서드 : ndarray.sort() => 원본 정렬됨 

- argOOO() 함수들
    - 해당 같이 있는 인덱스를 반환 
    - 예: ndarray.max() - 원소 중 가장 큰 값 ,    ndarray.argmax() : 원소 중 가장 큰 값의 인덱스

In [1]:
# -----------------------------------------
# 모듈 로딩
# -----------------------------------------
import numpy as np 

In [2]:
# -----------------------------------------
# 실습 array 생성
# -----------------------------------------
a1 = np.array([ [3,	1,	6],	
		        [0,	7,	4],	
		        [5,	3,	2]])

print( a1.shape)

(3, 3)


In [ ]:
# -----------------------------------------
# 정렬
# -----------------------------------------
## 함수 : np.sort()
as1 = np.sort(a1, axis=None)
print("정렬 전 ==>", a1.shape , a1 )
print("정렬 후 ==>\n", as1, end='\n\n')

as1 = np.sort(a1, axis=0)
print("행 기준 정렬 후 ==>\n",  as1, end='\n\n')

as1 = np.sort(a1, axis=1)
print("열 기준 정렬 후 ==>\n",  as1, end='\n\n')

정렬 전 ==> (3, 3) [[3 1 6]
 [0 7 4]
 [5 3 2]]
정렬 후 ==>
 [0 1 2 3 3 4 5 6 7]

행 기준 정렬 후 ==>
 [[0 1 2]
 [3 3 4]
 [5 7 6]]

열 기준 정렬 후 ==>
 [[1 3 6]
 [0 4 7]
 [2 3 5]]



In [15]:
## 메서드 : ndarray.sort() 원본 변경됨 
##         [기] axis=-1  : -1번 축 기준 오름차순 정렬 
print("정렬 전 ==>", a1 )

## -1번 축 기준 오름차순 정렬 즉, 행방향 정렬
a1.sort()
print("a1  ==>", a1 )

## 열방향 정렬
a1.sort(axis=0)
print("a1  ==>", a1 )


정렬 전 ==> [[0 3 5]
 [1 3 6]
 [2 4 7]]
a1  ==> [[0 3 5]
 [1 3 6]
 [2 4 7]]
a1  ==> [[0 3 5]
 [1 3 6]
 [2 4 7]]


In [ ]:
# -----------------------------------------
# 정렬 : 인덱스 반환 
# -----------------------------------------
## argsort() : 정렬 전 데이터가 있는 인덱스 반환
a1 = np.array([ [3,	1,	6],	
		        [0,	7,	4],	
		        [5,	3,	2]])

arr_idx = np.argsort(a1, axis=1)
print("정렬 전 인덱스 arr_idx : \n", arr_idx)

# 다차원 인덱스를 적용해 원래 배열을 정렬 시 : np.take_along_axis() 함수
sorted_a1 = np.take_along_axis(a1, arr_idx, axis=1)
print("정렬 후 : \n", sorted_a1)


# 1D 방식 정렬
# a1[arr_idx] ### <= 1D Array에 적합함


정렬 전 인덱스 arr_idx : 
 [[1 0 2]
 [0 2 1]
 [2 1 0]]
정렬 후 : 
 [[1 3 6]
 [0 4 7]
 [2 3 5]]


In [ ]:
#