In [1]:
2+2

4

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print(np.vstack([a, b]))
print(np.hstack([a, b]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.dstack((arr1, arr2))
print(result)
print(result.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.concatenate([a, b], axis=0))
print(np.concatenate([a, b], axis=1))
print(np.concatenate([a, b], axis=None))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[1 2 3 4 5 6 7 8]


In [5]:
arr = np.arange(12).reshape(3, 4)
h_splits = np.hsplit(arr, 2)
print(h_splits[0])
print(h_splits[1])

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [6]:
arr = np.arange(12).reshape(3, 4)
v_splits = np.vsplit(arr, 3)
print(v_splits[0])
print(v_splits[1])
print(v_splits[2])

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


In [7]:
arr = np.arange(12).reshape(3, 4)
h_splits = np.hsplit(arr, [1, 3])
print(h_splits[0])
print(h_splits[1])
print(h_splits[2])

[[0]
 [4]
 [8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3]
 [ 7]
 [11]]


In [8]:
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
copy_arr = arr.copy()
view_arr[0] = 100
copy_arr[1] = 200
print(arr)
print(view_arr)
print(copy_arr)

[100   2   3   4]
[100   2   3   4]
[  1 200   3   4]


In [9]:
x = np.array([1, 2, 3, 4, 5])
print(np.add.reduce(x))
print(np.multiply.reduce(x))
print(np.add.accumulate(x))

15
120
[ 1  3  6 10 15]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.add.reduceat(arr, [0, 3]))
print(np.multiply.reduceat(arr, [0, 2, 4]))

[ 6 15]
[ 2 12 30]


In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])
print(np.add(x, y))

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(np.greater(a, b))
print(np.logical_and(a > 1, b < 3))

[[11 22 33]
 [14 25 36]]
[False False  True]
[False  True  True]
