### [Numpy Basic] <hr>
- pandas와 numpy 이해


In [2]:
# 모듈 로딩
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# DF 생성
df= pd.DataFrame([[11, 22, 33], [44, 55, 66]])
df

,0,1,2
0,11,22,33
1,44,55,66


In [ ]:
# df 속성들
print(f'index: {df.index}')
print(f'columns: {df.columns}')
print(f'values: {type(df.values)}')

print(df.values)

index: RangeIndex(start=0, stop=2, step=1)
columns: RangeIndex(start=0, stop=3, step=1)
values: <class 'numpy.ndarray'>
[[11 22 33]
 [44 55 66]]


In [9]:
# SR 속성들
sr= df.iloc[0]

print(f'index: {sr.index}')
# print(f'columns: {sr.columns}')---> Series에는 columns 속성이 없다.
print(f'values: {type(sr.values)}')

print(sr.values)

index: RangeIndex(start=0, stop=3, step=1)
values: <class 'numpy.ndarray'>
[11 22 33]


- [ Ndarray 객체 생성 방법들 ] <hr>

In [10]:
# 모듈 로딩
import numpy as np


In [ ]:
# [방법 1] np.array() 함수 이용
# ========================================
arr1= np.array([11, 22, 33])

print(arr1) #리스트랑은 다름. 리스트는 쉼표가 있고, array는 쉼표가 없다.
print(f'shape: {arr1.shape}')
print(f'ndim: {arr1.ndim} D')
print(f'dtype: {arr1.dtype}')
print(f'itemsize: {arr1.itemsize} bytes')
print(f'data: {arr1.data}') #메모리 주소값이 나온다. array는 연속된 메모리 공간에 저장되기 때문에 주소값이 나온다.

[11 22 33]
shape: (3,)
ndim: 1 D
dtype: int64
itemsize: 8 bytes
data: <memory at 0x0000025375A49540>


In [ ]:
# [방법 1] np.array() 함수 이용
# ========================================
arr1= np.array([[11, 22, 33]]) # 괄호가 2개= 2차원 배열

print(arr1) #리스트랑은 다름. 리스트는 쉼표가 있고, array는 쉼표가 없다.
print(f'shape: {arr1.shape}')
print(f'ndim: {arr1.ndim} D')
print(f'dtype: {arr1.dtype}')
print(f'itemsize: {arr1.itemsize} bytes')
print(f'data: {arr1.data}') #메모리 주소값이 나온다. array는 연속된 메모리 공간에 저장되기 때문에 주소값이 나온다.
print(f'strides: {arr1.strides}') # (행 이동을 위한 메모리칸수, 열 이동을 위한 메모리칸수)


[[11 22 33]]
shape: (1, 3)
ndim: 2 D
dtype: int64
itemsize: 8 bytes
data: <memory at 0x000002537118D490>
strides: (24, 8)


In [26]:
 
arr1= np.array([[11, 22, 33], [44, 55, 66]], dtype=np.int16) # dtype을 지정해주면, 데이터 타입이 바뀐다. (기본값은 int64)

print(arr1) #리스트랑은 다름. 리스트는 쉼표가 있고, array는 쉼표가 없다.
print(f'shape: {arr1.shape}')
print(f'ndim: {arr1.ndim} D')
print(f'dtype: {arr1.dtype}')
print(f'itemsize: {arr1.itemsize} bytes')
print(f'data: {arr1.data}') #메모리 주소값이 나온다. array는 연속된 메모리 공간에 저장되기 때문에 주소값이 나온다.
print(f'strides: {arr1.strides}') # (행 이동을 위한 메모리칸수, 열 이동을 위한 메모리칸수)


[[11 22 33]
 [44 55 66]]
shape: (2, 3)
ndim: 2 D
dtype: int16
itemsize: 2 bytes
data: <memory at 0x000002537118D700>
strides: (6, 2)


In [28]:
# ========================================
# [방법 2] 특정값으로 채운 ndarray 생성
# ========================================
# 1) np.zeros() 함수 이용
arr1=np.zeros( (3,) ) # 3행 4열 2차원
arr2=np.zeros((2, 4)) # 1차원
arr3=np.zeros( (2, 4), dtype=np.int8 )

print(arr1)
print(arr2)
print(arr3)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]]


In [29]:
# np.ones() 함수 이용
arr1=np.ones( (3) ) 
arr2=np.ones((3, 2))
arr3=np.ones((3, 2), dtype=np.bool)

print(arr1)
print(arr2)
print(arr3)

[1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ True  True]
 [ True  True]
 [ True  True]]


In [34]:
# ========================================
# [방법 3] 범위 지정해서 ndarray 생성
# ========================================
# => np.arange() 함수 이용
arr1= np.arange(5)

# => np.linspace() 함수 이용
arr2, step=np.linspace(0, 5, retstep=True) # 0부터 5까지 1씩 증가하는 숫자들을 생성한다. (endpoint=False로 하면, 5는 포함되지 않는다.)

# => np.logspace() 함수 이용
arr3=np.logspace(0, 5, num=10) # 10개의 숫자들을 생성한다. (10^0부터 10^5까지)

print("arr1", arr1, sep="\n")
print("arr2", step, arr2, sep="\n")
print("arr3", arr3, sep="\n")



arr1
[0 1 2 3 4]
arr2
0.10204081632653061
[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
arr3
[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


In [ ]:
# np.full(): 원하는 특정 값으로 채운 ndarray 생성
arr1=np.full((2, 3), fill_value=7) # 2행 3열의 배열을 생성하고, 모든 원소를 7로 채운다.
print("arr1", arr1, sep="\n")


arr1
[[7 7 7]
 [7 7 7]]


In [38]:
# ========================================
# [방법 4] 특정 형태의 배열 객체 생성
# ========================================

np.empty((3, 2)) # 2행 3열의 배열을 생성하고, 모든 원소를 0으로 채운다. (초기화되지 않은 배열을 생성한다.)

# => np.empty_like() 함수 이용
arr2=np.empty_like(arr1) # arr1과 같은 형태의 배열을 생성한다. (초기화되지 않은 배열을 생성한다.)

arr2

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])