### [ Numpy Fancy Indexing ] <hr>

- 원하는 데이터의 인덱스를 배열/ 리스트에 담아서 한꺼번에 추출하는 인덱싱
- 예) 배열명[[인덱스, 인덱스]]


In [1]:
import numpy as np

In [6]:
# 실습 데이터
dataNP= np.array([[11, 22, 33], [44, 55, 66]], dtype= np.int8)

print(dataNP)

# 팬시 인덱싱=> 2번, 0번 컬럼 추출
dataNP[:, [2, 0]]= 9

print(dataNP)


[[11 22 33]
 [44 55 66]]
[[ 9 22  9]
 [ 9 55  9]]


In [8]:
# 팬시 인덱싱=> 1번, 0번 컬럼 추출
dataNP2= dataNP[[1, 0]]
print(dataNP2)

[[ 9 55  9]
 [ 9 22  9]]
