## [ Numpy - ndarray 원소 접근 ] <hr>

- 인덱싱 기반: 왼-> 오, 오-> 왼 2개 종류 인덱스
- 슬라이싱: 연속적이거나 일정한 규칙이 있는 원소 접근 방식

In [1]:
# 모듈 로딩
# ========================
import numpy as np


In [2]:
# 실습 데이터 생성
data= np.array([1, 2, 3, 4, 5])

In [4]:
print(data[0], type(data[0]), data[0].ndim) ## 0번 원소
print(data[-1], type(data[-1]), data[-1].ndim) ## 제일 마지막 원소


1 <class 'numpy.int64'> 0
5 <class 'numpy.int64'> 0


In [5]:
## 원소값 변경
data[0] = 10
print(data)

[10  2  3  4  5]


In [6]:
# ========================
# ndarray 원소 접근- 슬라이싱
# ========================

data[0:-2:2]

array([10,  3])

In [10]:
# ========================
# 슬라이싱+ 값 변경
# ========================
# view 타입: 값 변경 시 원본 데이터 변경 됨
data[0:-3]= 7
print(data)

# copy 타입: 값 변경 시 원본 데이터 변경 안됨
data2 = data[0:-3].copy()
data2[0] = 100
print(data)

# 값 출력
print(data)
print(data2)

[7 7 3 4 5]
[7 7 3 4 5]
[7 7 3 4 5]
[100   7]
