### [ 객체 탐지 모델 - haar Cascade ] <hr>

- [실습] 웃는 얼굴 감지 모델, 정면 얼굴 감지 모델 + 동영상/ 카메라

In [1]:
import cv2
import os
import matplotlib.pyplot as plt
import koreanize_matplotlib
import numpy as np
import matplotlib.cm as cm

In [5]:


# 동영상 또는 연결 카메라
VIDEO= '../Video/person_02.mp4'
CAM_ID=0 # 컴퓨터와 연결된 카메라 번호
F_NAME= 'person_smile_detect'

os.makedirs(F_NAME, exist_ok=True)

MODEL_FILE='../Haar/haarcascade_frontalface_alt2.xml'
MODEL_FILE1='../Haar/haarcascade_smile.xml'

detector= cv2.CascadeClassifier(MODEL_FILE)
detector1= cv2.CascadeClassifier(MODEL_FILE1)

In [ ]:
# 동영상 또는 연결 카메라
VIDEO= '../Video/person_02.mp4'
CAM_ID=0 # 컴퓨터와 연결된 카메라 번호
F_NAME= 'person_smile_detect'

os.makedirs(F_NAME, exist_ok=True)

MODEL_FILE='../Haar/haarcascade_frontalface_alt2.xml'
MODEL_FILE1='../Haar/haarcascade_smile.xml'

detector= cv2.CascadeClassifier(MODEL_FILE)
detector1= cv2.CascadeClassifier(MODEL_FILE1)

## 동영상 또는 카메라 객체 생성
cap= cv2.VideoCapture(VIDEO)

# 객체 초기화 연결 여부
if cap.isOpened():
    cnt=0
    while True:
        ret, img= cap.read()
        VideoNP= cv2.imread(Video)
        result= detector.detectMultiScale(cap)
        
        if ret:
            print(f'감지결과: {len(result)}개, {result}')

            cv2.imshow("person_smile_detect", img)
            cv2.imwrite(f'./{F_NAME}/{F_NAME}_{cnt:0>3}.jpg', img)
            cnt+=1
            cv2.waitKey(25)
        else:
            break
else:
    print(f'{VIDEO}: 연결 또는 초기화 실패')


## 동영상 또는 카메라 객체가 사용하는 메모리 해제

cap.release()

## 띄워진 창 모두 닫기
cv2.destroyAllWindows()

In [ ]:

# 동영상 또는 연결 카메라
VIDEO = '../Video/person_02.mp4'
CAM_ID = 0
F_NAME = 'person_detect'

os.makedirs(F_NAME, exist_ok=True)

MODEL_FILE = '../Haar/haarcascade_frontalface_alt2.xml'
# MODEL_FILE1 = '../Haar/haarcascade_smile.xml'

face_detector = cv2.CascadeClassifier(MODEL_FILE)
# smile_detector = cv2.CascadeClassifier(MODEL_FILE1)

cap = cv2.VideoCapture(VIDEO)

if cap.isOpened():
    cnt = 0

    while True:
        ret, img = cap.read()

        if not ret:
            break

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        faces = face_detector.detectMultiScale(
            gray,
            scaleFactor=1.1,
            minNeighbors=7,
            minSize=(30, 30)
        )

        print(f'얼굴 감지결과: {len(faces)}개, {faces}')

        for (x, y, w, h) in faces:
            cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)

            face_gray = gray[y:y + h, x:x + w]
            face_color = img[y:y + h, x:x + w]

            faces = face_detector.detectMultiScale(
                face_gray,
                scaleFactor=1.8,
                minNeighbors=20,
                minSize=(20, 20)
            )

        cv2.imshow("person_face_detect", img)
        cv2.imwrite(f'./{F_NAME}/{F_NAME}_{cnt:0>3}.jpg', img)

        cnt += 1

        if cv2.waitKey(25) & 0xFF == 27:
            break

else:
    print(f'{VIDEO}: 연결 또는 초기화 실패')

cap.release()
cv2.destroyAllWindows()

얼굴 감지결과: 4개, [[1206  465   56   56]
 [ 685  503   95   95]
 [1793  391   64   64]
 [1500  573  116  116]]
얼굴 감지결과: 4개, [[1597  406   46   46]
 [1205  462   59   59]
 [ 685  503   96   96]
 [1507  578  110  110]]
얼굴 감지결과: 2개, [[1517  584  108  108]
 [ 687  503   94   94]]
얼굴 감지결과: 4개, [[1210  463   53   53]
 [ 688  501   94   94]
 [1652  619   71   71]
 [1515  579  120  120]]
얼굴 감지결과: 3개, [[1656  622   76   76]
 [ 688  500   94   94]
 [1524  585  117  117]]
얼굴 감지결과: 3개, [[1663  629   66   66]
 [ 687  498   98   98]
 [1532  587  116  116]]
얼굴 감지결과: 5개, [[ 820  952   52   52]
 [1595  408   45   45]
 [1666  632   66   66]
 [ 691  497   96   96]
 [1538  589  116  116]]
얼굴 감지결과: 3개, [[1595  407   45   45]
 [ 693  495   96   96]
 [1540  588  118  118]]
얼굴 감지결과: 4개, [[1594  408   44   44]
 [1676  635   65   65]
 [ 694  494   96   96]
 [1549  591  114  114]]
얼굴 감지결과: 6개, [[1592  408   46   46]
 [1681  635   69   69]
 [1552  589  116  116]
 [ 907  735   61   61]
 [ 698  495   94   94]
 [1725  92