### [ 객체 탐지 모델-haar Cascade ] <hr>


- opencv에서 제공
- 정면 얼굴, 입, 눈, 상반신, 하반신 구분 가능


In [9]:
import cv2
import os
import matplotlib.pyplot as plt
import koreanize_matplotlib
import numpy as np
import matplotlib.cm as cm

In [10]:
## 이미지 데이터와 모델 파일

IMG_FILE='../Day03/image.png'
MODEL_FILE='../Haar/haarcascade_frontalface_alt2.xml'


In [ ]:
MODEL_FILE='../Haar/haarcascade_frontalface_alt2.xml'
detector= cv2.CascadeClassifier(MODEL_FILE)

imgNP= cv2.imread(IMG_FILE)
result= detector.detectMultiScale(imgNP)
print(f'감지결과: {len(result)}개, {result}')


감지결과: 4개, [[328 194  26  26]
 [292 170  28  28]
 [244 203  28  28]
 [193 165  27  27]]


In [19]:
x, y, w, h= result[3]
cv2.rectangle(imgNP, (x, y), (x+w, y+h), (255, 0, 0), 3)

cv2.imshow("detect", imgNP)
cv2.waitKey(4000)
cv2.destroyAllWindows()