### [ Numpy 파일 입출력 ] <hr>
- ndarray 객체를 파일로 저장
- 확장자: 1개의 파일-> 파일명.npy
    *  여러개의 파일-> 파일명.npz
    


In [1]:
import numpy as np

In [2]:
# 실습 데이터 생성
a1= np.linspace(1, 3)
a1


array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [7]:
# --------------------------------------
# ndarray 저장
# --------------------------------------

data_file= './data.npy'
all_file= './all.npz'
com_file='./com.npz'
text_file= './text.out'

# 1개 ndarray=> 파일로 저장
np.save(data_file, a1)

# 여러개 ndarray=> 파일로 저장
np.savez(all_file, a1, a1, a1)

# 여러개 ndarray=> 압축 후 파일로 저장
np.savez_compressed(com_file, x=a1, y=a1, z=a1)

# 여러개 ndarray=> 텍스트 파일로 저장
np.savetxt(text_file, a1)


In [14]:
# --------------------------------------
# ndarray 데이터 파일 읽기
# --------------------------------------
# 파일 1개 읽기
np.load(data_file)

# 파일 여러개 읽기
ret= np.load(all_file)
print(f'ret=> {type(ret)}')
print(f'files=> {ret.files}')
print(f'keys=> {ret.keys}')


# 텍스트로 저장된 파일 읽기
ret= np.loadtxt('text.out')
ret

ret=> <class 'numpy.lib.npyio.NpzFile'>
files=> ['arr_0', 'arr_1', 'arr_2']
keys=> <bound method NpzFile.keys of NpzFile './all.npz' with keys: arr_0, arr_1, arr_2>


array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

원본:  [ 3.2   0.1   8.   -5.2  -3.12]
반환결과=>  3.2 3.0
반환결과=>  0.1 0.0
반환결과=>  8.0 8.0
반환결과=>  -5.2 -6.0
반환결과=>  -3.12 -4.0


In [17]:
# -----------------------------------
# 누적 연산 처리 함수
# -----------------------------------
# => 연산.reduce(array_obj): 누적 연산 결과 반환 
arr= np.arange(1, 10, 3)
result= np.add.reduce(arr)
print(f'{arr}=> {result}')

result= np.multiply.reduce(arr)
print(f'{arr}=> {result}')


[1 4 7]=> 12
[1 4 7]=> 28


In [19]:
# => 연산.accumulate(array_obj): 누적 연산 값 반환 


result= np.add.accumulate(arr)
print(f'{arr}=> {result}')


[1 4 7]=> [ 1  5 12]


In [22]:
# -----------------------------------
# 누적 연산 처리 함수 - 2D ndarray
# -----------------------------------

arr= np.arange(1, 17).reshape(4, 4)

# => 2개 컬럼 묶어서 연산
retarr= np.add.reduceat(arr, [0, 2], axis=1)

print(f'{arr}\n ---연산 후---\n {retarr}')


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 ---연산 후---
 [[ 3  7]
 [11 15]
 [19 23]
 [27 31]]
