### [ ndarray 분할 ] <hr>
- np.hsplit(): 수평/컬럼을 분할하는 함수
- np.vsplit(): 수직/행을 분할하는 함수
- np.split(): axis 매개변수 설정에 따라 분할하는 함수

In [1]:
# 모듈 활성화
import numpy as np

In [3]:
# 실습 ndarray 생성
arr= np.arange(1, 13).reshape((3, 4))

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
## --------------------------
## 수평 분할
## --------------------------

a1, a2= np.hsplit(arr, 2) # 반환값은 리스트
print(a1, a2, sep='\n\n')

arr= np.arange(1, 13).reshape((3, 4))

#=> np.hsplit(array, (분할인덱스))
a1, a2, a3= np.hsplit(arr, (1, 3)) # 0~ (1-1), 1~ (3-1), 3~
print(a1, a2, a3, sep='\n\n')



[[ 1  2]
 [ 5  6]
 [ 9 10]]

[[ 3  4]
 [ 7  8]
 [11 12]]
[[1]
 [5]
 [9]]

[[ 2  3]
 [ 6  7]
 [10 11]]

[[ 4]
 [ 8]
 [12]]


In [11]:
## --------------------------
## 수직 분할
## --------------------------
arr= np.arange(18).reshape((6, 3))

a1, a2, a3= np.vsplit(arr, 3) # 반환값은 리스트
print(a1, a2, sep='\n\n')

#=> np.vsplit(array, (분할인덱스))
a1, a2, a3= np.vsplit(arr, (1, 3)) # 0~ (1-1), 1~ (3-1), 3~
print(a1, a2, a3, sep='\n\n')



[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]
[[0 1 2]]

[[3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
