### [ 유니버셜 함수- Numpy 성능 핵심 요소 ] <hr>
- 반복문 없이 원소 단위 연산 수행하는 함수
- 타입과 형태 변환 최적화 진행=> 브로드 캐스팅 자동 진행


In [1]:
import numpy as np

In [4]:
# 실습 데이터 생성
arr= np.array([3.2, 0.1, 8., -5.2, -3.12])
print(arr.dtype, arr.itemsize, arr.size,  sep=',')
print(arr)


float64,8,5
[ 3.2   0.1   8.   -5.2  -3.12]


In [10]:
# --------------------------------------
# 실수 데이터=> 소수점 이하 자릿수 관련 함수
# --------------------------------------
# => np.ceil(): 소수점 이하는 모두 올림 처리
print("원본: ", arr)

retarr= np.ceil(arr)
for idx in range(arr.size):
    print("반환결과=> ", arr[idx], retarr[idx])




원본:  [ 3.2   0.1   8.   -5.2  -3.12]
반환결과=>  3.2 4.0
반환결과=>  0.1 1.0
반환결과=>  8.0 8.0
반환결과=>  -5.2 -5.0
반환결과=>  -3.12 -3.0


In [12]:
# => np.round(): 소수점 이하 5이상 반올림 처리
print("원본: ", arr)

retarr= np.round(arr, 1)
for idx in range(arr.size):
    print("반환결과=> ", arr[idx], retarr[idx])


원본:  [ 3.2   0.1   8.   -5.2  -3.12]
반환결과=>  3.2 3.2
반환결과=>  0.1 0.1
반환결과=>  8.0 8.0
반환결과=>  -5.2 -5.2
반환결과=>  -3.12 -3.1


In [14]:
# => np.floor(): 소수점 이하 내림 처리
print("원본: ", arr)

retarr= np.floor(arr)
for idx in range(arr.size):
    print("반환결과=> ", arr[idx], retarr[idx])

원본:  [ 3.2   0.1   8.   -5.2  -3.12]
반환결과=>  3.2 3.0
반환결과=>  0.1 0.0
반환결과=>  8.0 8.0
반환결과=>  -5.2 -6.0
반환결과=>  -3.12 -4.0


In [17]:
# -----------------------------------
# 누적 연산 처리 함수
# -----------------------------------
# => 연산.reduce(array_obj): 누적 연산 결과 반환 
arr= np.arange(1, 10, 3)
result= np.add.reduce(arr)
print(f'{arr}=> {result}')

result= np.multiply.reduce(arr)
print(f'{arr}=> {result}')


[1 4 7]=> 12
[1 4 7]=> 28


In [19]:
# => 연산.accumulate(array_obj): 누적 연산 값 반환 


result= np.add.accumulate(arr)
print(f'{arr}=> {result}')


[1 4 7]=> [ 1  5 12]


In [22]:
# -----------------------------------
# 누적 연산 처리 함수 - 2D ndarray
# -----------------------------------

arr= np.arange(1, 17).reshape(4, 4)

# => 2개 컬럼 묶어서 연산
retarr= np.add.reduceat(arr, [0, 2], axis=1)

print(f'{arr}\n ---연산 후---\n {retarr}')


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 ---연산 후---
 [[ 3  7]
 [11 15]
 [19 23]
 [27 31]]
