### [2026_06_08]_과제 <hr>
- ch3: p55~p98
- 실습 코드 파일 업로드

In [1]:
import cv2
import os
import matplotlib.pyplot as plt
import koreanize_matplotlib
import numpy as np
import matplotlib.cm as cm



In [2]:
# ============================================================
# 1. NumPy 배열 생성 (3.1.3 값으로 생성)
# ============================================================

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
arr3 = np.array([1, 2, 3.14, 4])
arr4 = np.array([1, 2, 3, 4], dtype=np.float64)

print('arr1:', arr1, arr1.dtype, arr1.shape)
print('arr2:\n', arr2, arr2.dtype, arr2.shape)
print('arr3:', arr3, arr3.dtype, arr3.shape)
print('arr4:', arr4, arr4.dtype, arr4.shape)

arr1: [1 2 3 4] int64 (4,)
arr2:
 [[1 2 3 4]
 [5 6 7 8]] int64 (2, 4)
arr3: [1.   2.   3.14 4.  ] float64 (4,)
arr4: [1. 2. 3. 4.] float64 (4,)


In [3]:
# ============================================================
# 2. arange 생성과 dtype 확인
# ============================================================

arr5 = np.arange(5)
arr6 = np.arange(3.0)

print('arr5:', arr5, arr5.shape, arr5.dtype)
print('arr6:', arr6, arr6.shape, arr6.dtype)

arr5: [0 1 2 3 4] (5,) int64
arr6: [0. 1. 2.] (3,) float64


In [4]:
# ============================================================
# 3. empty, zeros, ones, full (3.1.4 크기와 초기값으로 생성)
# ============================================================

empty_arr = np.empty((2, 3))
empty_int = np.empty((2, 3), dtype=np.int16)
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((2, 3), dtype=np.float32)
full_arr = np.full((2, 3, 4), 255, dtype=np.uint8)

print('empty_arr:\n', empty_arr, empty_arr.dtype, empty_arr.shape)
print('empty_int:\n', empty_int, empty_int.dtype, empty_int.shape)
print('zeros_arr:\n', zeros_arr, zeros_arr.dtype, zeros_arr.shape)
print('ones_arr:\n', ones_arr, ones_arr.dtype, ones_arr.shape)
print('full_arr:\n', full_arr, full_arr.dtype, full_arr.shape)

empty_arr:
 [[ 6.95273773e-310 -2.00000191e+000  0.00000000e+000]
 [ 7.63966113e-223  1.94192680e+202  6.95268445e-310]] float64 (2, 3)
empty_int:
 [[31743 -1025 16384]
 [ 5120  1024     1]] int16 (2, 3)
zeros_arr:
 [[0. 0. 0.]
 [0. 0. 0.]] float64 (2, 3)
ones_arr:
 [[1. 1. 1.]
 [1. 1. 1.]] float32 (2, 3)
full_arr:
 [[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]] uint8 (2, 3, 4)


In [5]:
# ============================================================
# 4. 이미지와 같은 shape 배열 만들기
# ============================================================

if cv2 is not None:
    img_path = '../Images/cat_00.jpg'
    img = cv2.imread(img_path)

    if img is not None:
        empty_like_img = np.empty_like(img)
        zeros_like_img = np.zeros_like(img)
        ones_like_img = np.ones_like(img)
        full_like_img = np.full_like(img, 255)

        print('img shape:', img.shape, img.dtype)
        print('empty_like_img:', empty_like_img.shape, empty_like_img.dtype)
        print('zeros_like_img:', zeros_like_img.shape, zeros_like_img.dtype)
        print('ones_like_img:', ones_like_img.shape, ones_like_img.dtype)
        print('full_like_img:', full_like_img.shape, full_like_img.dtype)

img shape: (287, 285, 3) uint8
empty_like_img: (287, 285, 3) uint8
zeros_like_img: (287, 285, 3) uint8
ones_like_img: (287, 285, 3) uint8
full_like_img: (287, 285, 3) uint8


In [6]:
# ============================================================
# 5. dtype 변환
# ============================================================

arr7 = np.arange(10)
arr8 = arr7.astype('float32')
arr9 = np.uint8(arr8)
arr10 = arr9.astype(np.float64)

print('arr7:', arr7, arr7.dtype)
print('arr8:', arr8, arr8.dtype)
print('arr9:', arr9, arr9.dtype)
print('arr10:', arr10, arr10.dtype)

arr7: [0 1 2 3 4 5 6 7 8 9] int64
arr8: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float32
arr9: [0 1 2 3 4 5 6 7 8 9] uint8
arr10: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [7]:
# ============================================================
# 6. reshape, ravel, transpose
# ============================================================

arr11 = np.arange(6)
arr12 = arr11.reshape(2, 3)
arr13 = np.arange(24).reshape(2, 3, 4)
arr14 = np.arange(100).reshape(2, -1)
arr15 = np.arange(100).reshape(-1, 5)
arr16 = np.ravel(arr13)
arr17 = np.arange(10).reshape(2, -1)

print('arr11:', arr11, arr11.shape)
print('arr12:\n', arr12, arr12.shape)
print('arr13:\n', arr13, arr13.shape)
print('arr14:\n', arr14, arr14.shape)
print('arr15:\n', arr15, arr15.shape)
print('arr16:', arr16, arr16.shape)
print('arr17.T:\n', arr17.T)

arr11: [0 1 2 3 4 5] (6,)
arr12:
 [[0 1 2]
 [3 4 5]] (2, 3)
arr13:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)
arr14:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]] (2, 50)
arr15:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]] (20, 5)
arr16: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] (24,)
arr17.T:
 [[0 5]
 [1 6]
 [2

In [8]:
# ============================================================
# 7. 인덱싱
# ============================================================

arr18 = np.arange(10)
arr19 = np.arange(12).reshape(4, 3)

print('arr18:', arr18)
print('arr18[5]:', arr18[5])
print('arr18[2:7]:', arr18[2:7])
print('arr18[:5]:', arr18[:5])
print('arr18[5:]:', arr18[5:])
print('arr18[::2]:', arr18[::2])
print('arr18[::-1]:', arr18[::-1])

print('arr19:\n', arr19)
print('arr19[0, 0]:', arr19[0, 0])
print('arr19[1]:', arr19[1])
print('arr19[:, 1]:', arr19[:, 1])
print('arr19[1:3, 1:3]:\n', arr19[1:3, 1:3])


arr18: [0 1 2 3 4 5 6 7 8 9]
arr18[5]: 5
arr18[2:7]: [2 3 4 5 6]
arr18[:5]: [0 1 2 3 4]
arr18[5:]: [5 6 7 8 9]
arr18[::2]: [0 2 4 6 8]
arr18[::-1]: [9 8 7 6 5 4 3 2 1 0]
arr19:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr19[0, 0]: 0
arr19[1]: [3 4 5]
arr19[:, 1]: [ 1  4  7 10]
arr19[1:3, 1:3]:
 [[4 5]
 [7 8]]


In [9]:
# ============================================================
# 8. 리스트 연산과 NumPy 벡터 연산
# ============================================================

mylist = list(range(10))
print('mylist 원본:', mylist)

for i in range(len(mylist)):
    mylist[i] = mylist[i] + 1

print('mylist + 1:', mylist)

arr20 = np.arange(10)
print('arr20 원본:', arr20)
print('arr20 + 1:', arr20 + 1)



mylist 원본: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
mylist + 1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr20 원본: [0 1 2 3 4 5 6 7 8 9]
arr20 + 1: [ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# ============================================================
# 9. 스칼라 연산과 비교 연산
# ============================================================

arr21 = np.arange(5)
arr22 = arr21+ 5
arr23 = arr21- 2
arr24 = arr21* 2
arr25 = arr21/ 2
arr26 = arr22** 2
arr27 = arr22> 2

print('arr21:', arr21)
print('arr21+ 5:', arr22)
print('arr21- 2:', arr23)
print('arr21* 2:', arr24)
print('arr21/ 2:', arr25)
print('arr22** 2:', arr26)
print('arr22> 2:', arr27)

arr21: [0 1 2 3 4]
arr21+ 5: [5 6 7 8 9]
arr21- 2: [-2 -1  0  1  2]
arr21* 2: [0 2 4 6 8]
arr21/ 2: [0.  0.5 1.  1.5 2. ]
arr22** 2: [25 36 49 64 81]
arr22> 2: [ True  True  True  True  True]


In [11]:
# ============================================================
# 10. 이미지 배열 정보 확인
# ============================================================

if cv2 is not None:
    img_path = '../Images/boy_face.jpg'
    img = cv2.imread(img_path)

    if img is not None:
        print(type(img))
        print('ndim:', img.ndim)
        print('shape:', img.shape)
        print('size:', img.size)
        print('dtype:', img.dtype)
        print('itemsize:', img.itemsize)

<class 'numpy.ndarray'>
ndim: 3
shape: (600, 583, 3)
size: 1049400
dtype: uint8
itemsize: 1


In [ ]:
# ============================================================
# 11. 그레이스케일 이미지 직접 생성
# ============================================================

if cv2 is not None:
    gray_img = np.zeros((120, 120), dtype=np.uint8)

    gray_img[25:35, :] = 45
    gray_img[55:65, :] = 115
    gray_img[85:95, :] = 160
    gray_img[:, 35:45] = 205
    gray_img[:, 75:85] = 255

    cv2.imshow('Gray', gray_img)
    if cv2.waitKey(0) & 0xFF == 27:
        cv2.destroyAllWindows()



In [ ]:
# ============================================================
# 12. BGR 컬러 이미지 직접 생성
# ============================================================

if cv2 is not None:
    bgr_img = np.zeros((120, 120, 3), dtype=np.uint8)

    bgr_img[25:35, :] = [255, 0, 0]
    bgr_img[55:65, :] = [0, 255, 0]
    bgr_img[85:95, :] = [0, 0, 255]
    bgr_img[:, 35:45] = [255, 255, 0]
    bgr_img[:, 75:85] = [255, 0, 255]

    cv2.imshow('BGR', bgr_img)
    if cv2.waitKey(0) & 0xFF == 27:
        cv2.destroyAllWindows()

In [ ]:
# ============================================================
# 13. Matplotlib 기본 plot
# ============================================================

arr28 = np.array([2, 6, 7, 3, 12, 8, 4, 5])
plt.plot(arr28)
plt.show()

In [ ]:
# ============================================================
# 14. x, y 그래프
# ============================================================

x = np.arange(10)
y = x ** 2

plt.plot(x, y)
plt.show()


In [ ]:
# ============================================================
# 15. 선 색상 지정
# ============================================================

x = np.arange(10)
y = x ** 2

plt.plot(x, y, 'r')
plt.show()

# ============================================================
# 16. 여러 스타일 plot
# ============================================================

x = np.arange(10)
f1 = x * 5
f2 = x ** 2
f3 = x ** 2 + x * 2

plt.plot(x, 'r--')
plt.plot(f1, 'g.')
plt.plot(f2, 'bv')
plt.plot(f3, 'ks')
plt.show()

# ============================================================
# 17. subplot 그래프
# ============================================================

x = np.arange(10)

plt.subplot(2, 2, 1)
plt.plot(x, x ** 2)

plt.subplot(2, 2, 2)
plt.plot(x, x * 5)

plt.subplot(2, 2, 3)
plt.plot(x, np.sin(x))

plt.subplot(2, 2, 4)
plt.plot(x, np.cos(x))

plt.show()

In [ ]:

# ============================================================
# 18. OpenCV 이미지 Matplotlib로 출력
# ============================================================

if cv2 is not None:
    img_path = '../Images/blackpink.jpg'
    img = cv2.imread(img_path)

    if img is not None:
        plt.imshow(img)
        plt.show()

        plt.imshow(img[:, :, ::-1])
        plt.xticks([])
        plt.yticks([])
        plt.show()


# ============================================================
# 19. 여러 이미지 subplot 출력
# ============================================================

if cv2 is not None:
    img1 = cv2.imread('../Images/5shapes.jpg')
    img2 = cv2.imread('../Images/aircraft.jpg')
    img3 = cv2.imread('../Images/bts_01.jpg')

    if img1 is not None and img2 is not None and img3 is not None:
        plt.subplot(1, 3, 1)
        plt.imshow(img1[:, :, (2, 1, 0)])
        plt.xticks([])
        plt.yticks([])

        plt.subplot(1, 3, 2)
        plt.imshow(img2[:, :, (2, 1, 0)])
        plt.xticks([])
        plt.yticks([])

        plt.subplot(1, 3, 3)
        plt.imshow(img3[:, :, (2, 1, 0)])
        plt.xticks([])
        plt.yticks([])

        plt.show()
